---
title: "nonconformity"
format: html
editor: visual
---

## What is a index of Difformity

It is a index that signals how much a $\xi$ object of class $k$ differs from the typical $\langle \xi_k \rangle$ object of its own class $k$. Through this approssimation, this index indicates how the object is difform from its own class.

### Assumptions on the object

A $\xi$ object

1.  is characterised as a couple of vectors $(i,p)$ suche that

    1.  $i$ are observable

    2.  each $i$-trait is associated to a $p_i$ score

        1.  $p_i$ are normalised such that $\sum p_{i,\xi} = 1$

2.  $\xi$ is assigned to one and only one $k$ class

    1.  This relation is fixed over time and it never changes

### Assumptions on the typical object of the class

The $k$ class

1.  Has a typical object $\langle \xi_k \rangle$

2.  $\langle \xi_k \rangle$ can be individued through many methods

    1.  It could hold the approximation that $\langle \xi_k \rangle$ is identified in that couple of vectors $(i_{\langle \xi_k \rangle},p_{\langle \xi_k \rangle})$ where

        1.  All $i$ traits observed in $\xi$ elements of class $k$ are $i_{\langle \xi_k \rangle}$ traits of $\langle \xi_k \rangle$

        2.  $p_{i,\langle \xi_k \rangle}$ satifies the conditions to be apportioned to a average value of $p_{i,\xi \in k}$

        3.  Still holds that $\sum p_{i,\langle \xi_k \rangle} = 1$

    2.  Or $\langle \xi_k \rangle$ can be defined alternatively as any couple of vectors $(i_{\langle \xi_k \rangle},p_{\langle \xi_k \rangle})$ as long it holds $\sum p_{i,\langle \xi_k \rangle} = 1$

Under these conditions, to simplify notations, it is assumed that

-    $(i_{\langle \xi_k \rangle},p_{\langle \xi_k \rangle})$ can be recalled directly as $(i_{k},p_{k})$

## Operation

A $\xi$ object always a $k$ class. So it always exist

-   a vector of $i_\xi$ traits of the object

-   a vector of $i_k$ traits of the class of the object

A first operation is to identify the set $C_\xi = \cup (i_\xi,i_k)$

Difformity is defined as follow:

$$
\sum\limits_{i,j \in C_\xi } (|p_{i,k} - p_{i,\xi}|) \cdot (|p_{j,k} - p_{j,\xi}|) \cdot d_{i,j}
$$

where $d_{i,j}$ is a measure of dissimilarity between the trait $i$ and the trait $j$, such that $d_{i,i}$ = 0.

## Homeomorphism with (Inter)Disciplinarity

-   Papers are objects

-   Journals are classes

-   Disciplines are traits

    -   Scores are apportions of disciplinarity

This is not the only possible homemorphism. For example, papers can be still the objects (analytical units), then authors can be the classes since they satisfy the assumption to be a class.

More radically, instead of assuming that papers are the objects, it is possible to assume that authors are objects and their departments in a specific fixed time point are their class.

#### Notes on the homeomorphism

-   Disciplines, conventionally, DO NOT satisfy the condition to be classes since many objects can be multidisciplinary

-   Disciplines are defined as observable traits. In reality they act more as labels. The origin of this labelisation (i.e. the classification scheme) is not trivial.

-   Canonically, disciplinary labelisation is operated through the reference lists of papers. This operation is understood as an observation of what the paper is intending to cognitively integrate.

    -   Nevertheless, a very similar operation can be performed over the semantics of the paper, and it would still catch how the paper is trying to integrate disparate sources of concepts, data, theories, etc.

## Example
